name: EAS Build
on: push

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[build]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: Setup git
        run: git config --global user.email "yuta322@gmail.com" && git config --global user.name "Yuta Hidaka"

      - name: Setup standard version
        run: yarn add --dev standard-version@next standard-version-expo

      - name: Update standard version
        run: yarn standard-version --release-as minor

      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Build on EAS
        run: npx eas-cli build --platform all --non-interactive
