name: EAS Build
on: push

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[build]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup git
        run: git config --global user.email "yuta322@gmail.com" && git config --global user.name "Yuta Hidaka"

      - name: Setup standard version
        run: yarn add --dev standard-version@next standard-version-expo

      - name: Update standard version
        run: yarn standard-version --release-as patch

      - name: Git push
        run: git push

      - name: Install dependencies
        run: yarn install

      # - name: 🚀 Create update
      #   env:
      #     NODE_OPTIONS: "--openssl-legacy-provider"
      #   run: eas update --auto --non-interactive

      - name: 🚀🚀🚀🚀🚀 Build on EAS 🚀🚀🚀🚀🚀
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: npx eas-cli build --platform all --non-interactive --auto-submit --no-wait
